### ISSUE TITLE
Hex Viewer/Editor

### ISSUE THREAD

**Issue by emad-elsaid** [emad-elsaid/devtools#2]
As javascript now has the FileReader we can use it to read binary files and view it like any desktop hex viewer 
https://en.wikipedia.org/wiki/Hex_editor
## initial features
- open a binary file and view words as hex/ascii
- edit byte by byte
- search and replace
- download new modified file
## further enhancements
- copy/paste chunks of bytes
- switch hex viewer to binary/oct
- comparing two files and show diff between them
- export data to html/text format
- bitwise operations on chunk of bytes

**Comment by blazeeboy** [comment]
Next up is Search and replace feature
